export default {
	HOME: '/',
	LOGIN: '/login',
	LOGOUT: '/logout',
	SIGNUP: '/signup',
	RESET_PASSWORD: '/reset',
	FORGOT_PASSWORD: '/forgot',
	EDIT_PROFILE: '/member/:id/edit',
	EVENTS: '/events',
	EVENT: '/event/:id',
	CREATE_EVENT: '/events/create',
	EDIT_EVENT: '/event/:id/edit',
	CHECKIN_EVENT: '/event/:id/checkin',
	MEMBERS: '/members',
	MEMBER: '/member/:id',
	CALENDAR: '/calendar',
	REPORTS: '/reports',
	PERMISSIONS: '/permissions',
	PERMISSION: '/permission/:id',
	CREDENTIALS: '/credentials',
	LOCATIONS: '/locations',
	LOCATIONS_MAP: '/locations/map',
	LOCATION: '/location/:id',
	HACKATHONS: '/hackathons',
	PROJECTS: '/projects',
	DEV: '/dev',
	ANVIL_WIFI: '/anvil-wifi'
};
